 sudo: false
 language: python

 python:
     - "2.7"

 addons:
     apt:
        packages:
            - ncftp

 cache:
     directories:
         - "~/.platformio"

 install:
     - pip install -U platformio

 script:
     - platformio run --project-dir fw
     - echo "`date +%Y-%m-%d_%H-%M-%S`;$TRAVIS_BRANCH;$TRAVIS_BUILD_NUMBER;$TRAVIS_COMMIT;$TRAVIS_BUILD_ID" > fw/pub/meta.txt
     - ncftpput -u $FTPUSER -p $FTPPASS -m jslab.net /`date +%Y-%m-%d_%H-%M-%S` fw/pub/*
